config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'managements#result'
  get 'schedule', to: 'managements#schedule'
  get 'ranking', to: 'managements#ranking'
  get 'matches/:id', to: 'managements#show'
  get 'matches/:id/edit', to: 'managements#edit'
  patch 'matches/:id', to: 'managements#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :teams
end

app/models/match.rb
class Match < ApplicationRecord
end

app/models/result.rb
class Result < ApplicationRecord
  has_one :team
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :group
  has_one :result
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  
  def result
    @groups = Group.all
    @teams = Team.all
    @results = Result.all
  end

  def schedule
    @teams = Team.all
    @results = Result.all
    @referee_headquarters = "本部"
    @referee_lose_team = "負け審"
  end

  def ranking
  end

  def show
    @result = Result.find(params[:id])
  end

  def edit
    @result = Result.find(params[:id])
  end

  def update
    @result = Result.find(params[:id])
    @result.update(params.require(:result).permit(:home_team_score, :away_team_score))
    if @result.home_team_score > @result.away_team_score
      @result.update!(home_team_point: 3, away_team_point: 0)
    elsif @result.home_team_score == @result.away_team_score
      @result.update!(home_team_point: 1, away_team_point: 1)
    else
      @result.update!(home_team_point: 0, away_team_point: 3)
    end
    redirect_to schedule_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managements_helper.rb
module ManagementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FSC202012</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/css/uikit.min.css" />
    <!-- UIkit JS -->

  </head>
  <body>
    <div class="header">
      <h3>FSC Futsal Tournament</h3>
    </div>
    <div class="contents">
      <div class="left-content">
        <%= yield %>
      </div>
      <div class="right-content">
        <div class="navbar">
          <h5>2020/12 FSC Futsal Tournament</h5>
          <ul class="uk-list uk-list-divider">
            <li><%= link_to "試合結果", root_path %></li>
            <li><%= link_to "タイムスケジュール", schedule_path %></li>
            <li><%= link_to "得点ランキング", ranking_path %></li>
          </ul>
        </div>
      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.3/js/uikit-icons.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12/dist/vue.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-tournament-bracket@2.1.2/dist/vue-tournament-bracket.umd.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script>
      jQuery(function($){
        $('.tab').click(function(){
          $('.is-active').removeClass('is-active');
          $(this).addClass('is-active');
          $('.is-show').removeClass('is-show');
          // クリックしたタブからインデックス番号を取得
          const index = $(this).index();
          // クリックしたタブと同じインデックス番号をもつコンテンツを表
          $('.panel').eq(index).addClass('is-show');
        });
      });
    </script>
  </body>
</html>

app/views/managements/edit.html.erb
<h3>試合結果</h3>
<table class="uk-table uk-table-small uk-table-divider">
  <tbody>
    <tr>
      <%= form_for @result, url: {action: "update"} do |f| %>
        <td><%= @result.home_team_id %></td>
        <td><%= f.text_field :home_team_score %></td>
        <td><%= f.text_field :away_team_score %></td>
        <td><%= @result.away_team_id %></td>
        <%= f.submit "登録" %>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/managements/ranking.html.erb
<h3>得点ランキング</h3>
<table class="uk-table uk-table-small uk-table-divider">
  <thead>
    <tr>
      <th>得点ランキング</th>
      <th>得点者</th>
      <th>得点数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>メッシ</td>
      <td>10</td>
    </tr>
    <tr>
      <td>2</td>
      <td>ロナウド</td>
      <td>9</td>
    </tr>
    <tr>
      <td>3</td>
      <td>ネイマール</td>
      <td>8</td>
    </tr>
    <tr>
      <td>4</td>
      <td>本田</td>
      <td>5</td>
    </tr>
    <tr>
      <td>5</td>
      <td>香川</td>
      <td>3</td>
    </tr>
  </tbody>
</table>

app/views/managements/result.html.erb
<div class="uk-container-small">
<div id="app">
  <bracket :rounds="rounds">
    <template #player="{ player }">
      <span>{{ player.name }}</span>
    </template>
  </bracket>
</div>
  <div class="result-header-bg">
    <h3 class="uk-text-center result-header-text">試合結果</h3>
  </div>
  <% @groups.each do |group| %>
    <h4 class="uk-heading-divider">グループ<%= group.group_number %></h4>
    <table class="uk-table uk-table-small uk-table-divider">
      <thead>
        <tr>
          <th>順位</th>
          <th>チーム名</th>
          <th>勝点</th>
          <th>勝</th>
          <th>引</th>
          <th>敗</th>
          <th>得点</th>
          <th>失点</th>
          <th>得失点</th>
        </tr>
      </thead>
      <tbody>
        <% @teams_based_on_group = @teams.where(group_id: group.id) %>
        <% @teams_based_on_group.each do |team| %>
          <tr>
            <% home_win_point = @results.where(home_team_id: team.id, home_team_point: 3) %>
            <% away_win_point = @results.where(away_team_id: team.id, away_team_point: 3) %>
            <% win_point = home_win_point.count + away_win_point.count%>
            <% home_draw_point = @results.where(home_team_id: team.id, home_team_point: 1) %>
            <% away_draw_point = @results.where(away_team_id: team.id, away_team_point: 1) %>
            <% draw_point = home_draw_point.count + away_draw_point.count%>
            <% home_lose_point = @results.where(home_team_id: team.id, home_team_point: 0) %>
            <% away_lose_point = @results.where(away_team_id: team.id, away_team_point: 0) %>
            <% lose_point = home_lose_point.count + away_lose_point.count%>
            <% sum_point = win_point * 3 + draw_point * 1 %>
            <% home_get_score = @results.where(home_team_id: team.id) %>
            <% home_get_scores = home_get_score.all.sum(:home_team_score) %>
            <% away_get_score = @results.where(away_team_id: team.id) %>
            <% away_get_scores = away_get_score.all.sum(:away_team_score) %>
            <% total_get_scores = home_get_scores + away_get_scores %>
            <% home_lost_score = @results.where(home_team_id: team.id) %>
            <% home_lost_scores = home_lost_score.all.sum(:away_team_score) %>
            <% away_lost_score = @results.where(away_team_id: team.id) %>
            <% away_lost_scores = away_lost_score.all.sum(:home_team_score) %>
            <% total_lost_scores = home_lost_scores + away_lost_scores %>
            <% goal_difference = total_get_scores - total_lost_scores %>

            <td>1</td>
            <td><%= team.name %></td>
            <td><%= sum_point %></td>
            <td><%= win_point %></td>
            <td><%= draw_point %></td>
            <td><%= lose_point %></td>
            <td><%= total_get_scores %></td>
            <td><%= total_lost_scores %></td>
            <td><%= goal_difference %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/managements/schedule.html.erb
<h3>タイムスケジュール</h3>
<!--タブ-->
<ul class="tab-group">
  <li class="tab is-active">Aコート</li>
  <li class="tab">Bコート</li>
  <li class="tab">Cコート</li>
</ul>

<!--タブを切り替えて表示するコンテンツ-->
<div class="panel-group">
  <div class="panel is-show">
    <table class="uk-table uk-table-small uk-table-divider">
      <thead>
        <tr>
          10:00- 受付開始<br>
          11:00- 開会式
          <th></th>
          <th>試合開始時間</th>
          <th>Aコート</th>
          <th>審判(A)</th>
          <th></th>
        </tr>
      </thead>
      <% @results_Acourt = @results.where(court: 0).order(:id) %>
      <% match_num = 0 %>
      <% @results_Acourt.each do |result| %> 
        <tbody>
          <tr>
            <% home_teamA = @teams.find_by(id: result.home_team_id) %>
            <% away_teamA = @teams.find_by(id: result.away_team_id) %>
            <% match_num += 1 %>
            <td><%= match_num %></td>
            <td>11:25</td>
            <td><%= home_teamA.name %><br>vs<br><%= away_teamA.name %> </td>
            <% if result.id == 1 %>
              <td><%=@referee_headquarters %></td>
            <% else %>
              <td><%=@referee_lose_team %></td>
            <% end %>
          <td><%= link_to "登録する", controller: 'managements', action: 'edit', id: result.id %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
  <div class="panel">
    <table class="uk-table uk-table-small uk-table-divider">
      <thead>
        <tr>
          10:00- 受付開始<br>
          11:00- 開会式
          <th></th>
          <th>試合開始時間</th>
          <th>Bコート</th>
          <th>審判(B)</th>
          <th></th>
        </tr>
      </thead>
      <% @results_Bcourt = @results.where(court: 1).order(:id) %>
      <% match_num = 0 %>
      <% @results_Bcourt.each do |result| %>
        <tbody>
          <tr>
            <% home_teamB = @teams.find_by(id: result.home_team_id) %>
            <% away_teamB = @teams.find_by(id: result.away_team_id) %>
            <% match_num += 1 %>
            <td><%= match_num %></td>
            <td>11:25</td>
            <td><%= home_teamB.name %><br>vs<br><%= away_teamB.name %></td>
            <% if result.id == 2 %>
              <td><%=@referee_headquarters %></td>
            <% else %>
              <td><%=@referee_lose_team %></td>
            <% end %>
            <td><%= link_to "登録する", controller: 'managements', action: 'edit', id: result.id %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
  <div class="panel">
    <table class="uk-table uk-table-small uk-table-divider">
      <thead>
        <tr>
          10:00- 受付開始<br>
          11:00- 開会式
          <th></th>
          <th>試合開始時間</th>
          <th>Cコート</th>
          <th>審判(C)</th>
          <th></th>
        </tr>
      </thead>
      <% @results_Ccourt = @results.where(court: 2).order(:id) %>
      <% match_num = 0 %>

      <% @results_Ccourt.each do |result| %>
        <tbody>
          <tr>
            <% home_teamC = @teams.find_by(id: result.home_team_id) %>
            <% away_teamC = @teams.find_by(id: result.away_team_id) %>
            <% match_num += 1 %>
            <td><%= match_num %></td>
            <td>11:25</td>
            <td><%= home_teamC.name %><br>vs<br><%= away_teamC.name %></td>
            <% if result.id == 3 %>
              <td><%=@referee_headquarters %></td>
            <% else %>
              <td><%=@referee_lose_team %></td>
            <% end %>
            <td><%= link_to "登録する", controller: 'managements', action: 'edit', id: result.id %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/managements/show.html.erb
<h3>試合結果</h3>
<table class="uk-table uk-table-small uk-table-divider">
  <tbody>
    <tr>
      <td><%= @result.home_team_id %></td>
      <td><%= @result.home_team_score %></td>
      <td><%= @result.away_team_score %></td>
      <td><%= @result.away_team_id %></td>
    </tr>
  </tbody>
</table>